#!/bin/bash

# =============================================================================
# AWS Database Setup Script for Converge Global Backend
# =============================================================================
# This script helps you set up your AWS RDS database for the first time.
# It will guide you through the process of creating the necessary environment
# file and seeding your database.
# =============================================================================

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Function to print colored output
print_header() {
    echo -e "${PURPLE}=============================================================================${NC}"
    echo -e "${PURPLE}$1${NC}"
    echo -e "${PURPLE}=============================================================================${NC}"
}

print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_menu() {
    echo -e "${CYAN}$1${NC}"
}

# Function to check if required tools are installed
check_dependencies() {
    print_status "Checking dependencies..."
    
    local missing_tools=()
    
    if ! command -v psql &> /dev/null; then
        missing_tools+=("psql (PostgreSQL client)")
    fi
    
    if ! command -v aws &> /dev/null; then
        missing_tools+=("aws (AWS CLI)")
    fi
    
    if [ ${#missing_tools[@]} -ne 0 ]; then
        print_error "Missing required tools:"
        for tool in "${missing_tools[@]}"; do
            echo "  - $tool"
        done
        echo ""
        print_error "Please install the missing tools and try again."
        echo ""
        print_status "Installation instructions:"
        echo "  - PostgreSQL client: https://www.postgresql.org/download/"
        echo "  - AWS CLI: https://aws.amazon.com/cli/"
        exit 1
    fi
    
    print_success "All dependencies are available"
}

# Function to get AWS RDS endpoint
get_rds_endpoint() {
    print_status "Getting AWS RDS endpoint from Terraform..."
    
    if [ -f "$PROJECT_ROOT/terraform/terraform.tfstate" ]; then
        local endpoint=$(cd "$PROJECT_ROOT/terraform" && terraform output -raw db_endpoint 2>/dev/null || echo "")
        if [ -n "$endpoint" ]; then
            print_success "Found RDS endpoint: $endpoint"
            echo "$endpoint"
            return 0
        fi
    fi
    
    print_warning "Could not automatically detect RDS endpoint from Terraform"
    return 1
}

# Function to create environment file
create_env_file() {
    print_header "Creating Environment File"
    
    local env_file="$PROJECT_ROOT/.env"
    
    if [ -f "$env_file" ]; then
        print_warning "Environment file already exists: $env_file"
        read -p "Do you want to overwrite it? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            print_status "Keeping existing environment file"
            return 0
        fi
    fi
    
    print_status "Creating environment file..."
    
    # Try to get RDS endpoint automatically
    local db_host
    if db_host=$(get_rds_endpoint); then
        print_success "Using RDS endpoint: $db_host"
    else
        read -p "Enter your AWS RDS endpoint (e.g., your-db.abc123.us-east-1.rds.amazonaws.com): " db_host
    fi
    
    # Get other database parameters
    read -p "Enter database port (default: 5432): " db_port
    db_port=${db_port:-5432}
    
    read -p "Enter database name (default: converge_staging_db): " db_name
    db_name=${db_name:-converge_staging_db}
    
    read -p "Enter database username (default: postgres): " db_user
    db_user=${db_user:-postgres}
    
    read -s -p "Enter database password: " db_password
    echo
    
    # Get other configuration
    read -p "Enter Node environment (default: staging): " node_env
    node_env=${node_env:-staging}
    
    read -p "Enter application port (default: 3000): " app_port
    app_port=${app_port:-3000}
    
    # Create the .env file
    cat > "$env_file" << EOF
# AWS Deployment Environment Variables
# Generated by setup-aws-db.sh on $(date)

# Application
NODE_ENV=$node_env
PORT=$app_port

# AWS RDS Database Configuration
DB_HOST=$db_host
DB_PORT=$db_port
DB_NAME=$db_name
DB_USER=$db_user
DB_PASSWORD=$db_password

# Cloud Provider
CLOUD_PROVIDER=aws

# Google Cloud (for AI services - still needed for Vertex AI/Gemini)
GCP_PROJECT_ID=your-gcp-project-id
VERTEX_AI_LOCATION=us-central1
GOOGLE_GEMINI_API_KEY=your-gemini-api-key

# AWS Region
AWS_REGION=us-east-1
EOF

    print_success "Environment file created: $env_file"
    
    # Make sure the file is not readable by others
    chmod 600 "$env_file"
    print_status "Set file permissions to 600 (owner read/write only)"
}

# Function to test database connection
test_database_connection() {
    print_header "Testing Database Connection"
    
    # Load environment variables
    source "$PROJECT_ROOT/.env"
    
    print_status "Testing connection to: $DB_HOST:$DB_PORT/$DB_NAME"
    
    export PGPASSWORD="$DB_PASSWORD"
    
    if psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -c "SELECT 1;" > /dev/null 2>&1; then
        print_success "Database connection successful!"
        return 0
    else
        print_error "Database connection failed!"
        print_error "Please check your database credentials and network connectivity"
        return 1
    fi
}

# Function to show next steps
show_next_steps() {
    print_header "Next Steps"
    
    echo -e "${CYAN}Your AWS database setup is complete! Here's what you can do next:${NC}"
    echo ""
    echo "1. ${GREEN}Seed your database:${NC}"
    echo "   ./scripts/db-manager.sh"
    echo "   (Choose option 3 for telecom products or option 4 for wine business)"
    echo ""
    echo "2. ${GREEN}Test your application:${NC}"
    echo "   npm run dev"
    echo "   (Make sure your application can connect to the database)"
    echo ""
    echo "3. ${GREEN}Run database management:${NC}"
    echo "   ./scripts/db-manager.sh"
    echo "   (For backup, restore, and other database operations)"
    echo ""
    echo "4. ${GREEN}Deploy to AWS:${NC}"
    echo "   cd terraform && terraform apply"
    echo "   (If you haven't already deployed your infrastructure)"
    echo ""
    echo -e "${YELLOW}Important Notes:${NC}"
    echo "  - Your database credentials are stored in .env (keep this file secure)"
    echo "  - Make sure your AWS security groups allow connections from your IP"
    echo "  - Consider setting up automated backups for production"
    echo ""
}

# Main execution
main() {
    print_header "AWS Database Setup for Converge Global Backend"
    
    echo -e "${CYAN}This script will help you set up your AWS RDS database.${NC}"
    echo -e "${CYAN}Make sure you have:${NC}"
    echo "  - AWS RDS PostgreSQL instance running"
    echo "  - Database credentials"
    echo "  - Network access to your RDS instance"
    echo ""
    
    read -p "Continue with setup? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        print_status "Setup cancelled by user"
        exit 0
    fi
    
    check_dependencies
    create_env_file
    
    if test_database_connection; then
        print_success "Database setup completed successfully!"
        show_next_steps
    else
        print_error "Database setup failed. Please check your configuration and try again."
        exit 1
    fi
}

# Run main function
main "$@"
